name: Build
run-name: 'Build: @${{ github.ref_name }}'
on:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GH_USER: 'github-actions[bot]'

jobs:
  build:
    name: Build applications
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: mato533/cicd-actions/setup-pnpm@main
        with:
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --provenance --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate changelog for the Release
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run changelog -c cliff-github.toml -l
          pnpm exec prettier --write CHANGELOG.md

      - name: Create Release
        env:
          GIT_TAG: ${{ github.ref_name }}
        run: gh release create "${GIT_TAG}" ./*.tgz --draft=false -t "${GIT_TAG}" -F CHANGELOG.md

  coverage:
    name: Upload the coverage
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: mato533/cicd-actions/setup-pnpm@main
        with:
          cache: 'pnpm'

      - name: Run the coverage
        run: pnpm run coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          verbose: true
