name: Run Test
run-name: 'TEST@${{github.ref_name}}'
on:
  workflow_call:

  push:
    branches:
      - main
    paths:
      - '*'
      - src/**
      - '!**.md'
concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test & build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x]
    steps:
      - uses: mato533/cicd-actions/setup-pnpm@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Type check
        run: pnpm run typecheck

      - name: Run the test
        run: pnpm run test

      - name: Build
        run: pnpm run build

  coverage:
    name: Upload coverage to code climate
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.event_name == 'push'
    steps:
      - uses: mato533/cicd-actions/setup-pnpm@main
        with:
          cache: 'pnpm'

      - uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm exec vitest run --coverage
          coverageLocations: ${{github.workspace}}/coverage/clover.xml:clover
